---
- name: set vars
  hosts: etwas
  become: yes
  vars_files:
    - group_vars/etwas.yml

- name: set vars
  hosts: pilz
  become: yes
  vars_files:
    - group_vars/pilz.yml

- name: Tor-Relay setup
  hosts: relays
  become: yes

  roles:
    # - install-and-configure-tor
    # - autorestart
    - firewall
    # - autorestart
    # - confswap
    # - set-hostname
    # - hifis.unattended_upgrades
    # - pkgs
    # - ssh
    # - update-upgrade-all
    # - setup-apparmor
    # - set-family
    # - devsec.hardening.os_hardening
    # - sshharden
    # - backup-keys
    # - prometheus.prometheus.fail2ban_exporter
    # - monitoring