---
- name: set vars
  hosts: etwas
  become: yes
  vars_files:
    - group_vars/etwas.yml

- name: set vars
  hosts: pilz
  become: yes
  vars_files:
    - group_vars/pilz.yml

- name: Tor-Relay setup
  hosts: relays
  become: yes

  roles:
    - firewall
    - autorestart
    - confswap
    - install-and-configure-tor
    - set-hostname
    - oefenweb.fail2ban
    - hifis.unattended_upgrades
    - pkgs
    - ssh
    - update-upgrade-all
    - setup-apparmor
    - set-family
    - devsec.hardening.os_hardening
    - sshharden
    - backup-keys
    - prometheus.prometheus.fail2ban_exporter
    - monitoring
