---
- name: set vars
  hosts: etwas
  become: yes
  vars_files:
    - group_vars/etwas.yml

- name: set vars
  hosts: pilz
  become: yes
  vars_files:
    - group_vars/pilz.yml

- name: upgrade-trixie
  hosts: relays
  become: yes

  roles:
  #  - pkgs
    - upgrade-trixie