---
- name: Ensure ufw is installed
  become: yes
  ansible.builtin.apt:
    name: ufw
    state: present

- name: reset ufw
  community.general.ufw:
    state: reset

- name: deny everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    log: true

- name: Allow access for specified IPv4 ranges
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
    insert_relative_to: first-ipv4
  loop:
    - 130.83.0.0/16
    - 94.142.240.0/21

- name: Allow access for specified IPv6 ranges
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
    insert_relative_to: first-ipv6
  loop:
    - 2a0e:8f02:f017::/48
    - 2a01:c00::/26
    - 2001:41b8::/29
    - 2a02:3000::/23

- name: deny incoming by default
  community.general.ufw:
    rule: deny
    port: 9100
    insert_relative_to: last-ipv4

- community.general.ufw:
    rule: allow
    name: OpenSSH

- community.general.ufw:
    rule: allow
    port: '443'  # Tor

- community.general.ufw:
    state: reloaded