---
- name: Ensure apt-transport-https is installed
  become: yes
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes
- name: Ensure gnupg is installed
  become: yes
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: yes
- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89) #credits; https://github.dev/nusenu/ansible-relayor
  become: yes
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present
    keyring: /usr/share/keyrings/deb.torproject.org-keyring.gpg
- name: Ensure Tor sources list is non-existent
  become: yes
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/tor.list  
    state: absent
- name: Add Tor repositories
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: tor
  loop:
    - repo: "deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"
    - repo: "deb-src [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"
- name: Install Tor packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: present
    update_cache: yes
  loop:
    - package: deb.torproject.org-keyring
    - package: tor
    - package: nyx
- name: Install Tor packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: present
    update_cache: yes
  loop:
    - package: deb.torproject.org-keyring
    - package: tor
    - package: nyx
- name: Place torrc configuration file
  become: yes
  vars:
    ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
    ipv6_address: "{{ ansible_default_ipv6.address | default(ansible_all_ipv6_addresses[0]) }}"
  ansible.builtin.template:
    src: ../files/torrc.j2
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: '0644'
  register: tor_config
- name: Restart Tor service
  ansible.builtin.include_role:
    name: restart-tor
  when: tor_config.changed
- name: Install automatic upgrade packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: present
    update_cache: yes
  loop:
    - package: unattended-upgrades
    - package: apt-listchanges
- name: Copy upgrade policies
  become: yes
  ansible.builtin.copy:
    src: ../files/{{ item.file }}
    dest: /etc/apt/apt.conf.d/{{ item.file }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - file: 50unattended-upgrades
    - file: 20auto-upgrades
