---
- name: add authorized keys
  hosts: relays
  become: yes
  tasks:
    - name: Set authorized keys taken from url
      authorized_key:
        user: root
        state: present
        key: https://github.com/pilz0.keys